# Generated by Django 5.2.2 on 2025-07-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sname', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=500)),
            ],
        ),
    ]
